import { useState } from 'react';
import { Download, FileText, Image, Mail, Share2 } from 'lucide-react';

export default function AnalyticsExport({ orders, restaurant, analytics }) {
  const [exporting, setExporting] = useState(false);
  const [exportFormat, setExportFormat] = useState('csv');

  const exportToCSV = () => {
    const headers = ['Date', 'Order ID', 'Customer', 'Items', 'Amount', 'Type', 'Status'];
    const rows = orders.map(order => [
      new Date(order.createdAt).toLocaleDateString(),
      order._id,
      order.customerName,
      order.items?.map(i => `${i.name} x${i.quantity}`).join('; '),
      order.totalAmount,
      order.orderType,
      order.status
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${restaurant.name}_analytics_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const exportToJSON = () => {
    const data = {
      restaurant: {
        name: restaurant.name,
        rating: restaurant.rating,
        cuisine: restaurant.cuisine
      },
      exportDate: new Date().toISOString(),
      summary: {
        totalOrders: orders.length,
        totalRevenue: orders.reduce((sum, o) => sum + o.totalAmount, 0),
        avgOrderValue: orders.length > 0 ? orders.reduce((sum, o) => sum + o.totalAmount, 0) / orders.length : 0
      },
      orders: orders.map(order => ({
        id: order._id,
        date: order.createdAt,
        customer: order.customerName,
        phone: order.customerPhone,
        items: order.items,
        total: order.totalAmount,
        type: order.orderType,
        status: order.status
      })),
      analytics: analytics
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${restaurant.name}_analytics_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const generateReport = () => {
    const totalRevenue = orders.reduce((sum, o) => sum + o.totalAmount, 0);
    const avgOrderValue = orders.length > 0 ? totalRevenue / orders.length : 0;
    
    const report = `
# ${restaurant.name} - Analytics Report
Generated: ${new Date().toLocaleString()}

## Summary
- Total Orders: ${orders.length}
- Total Revenue: ₹${totalRevenue.toLocaleString()}
- Average Order Value: ₹${Math.round(avgOrderValue).toLocaleString()}
- Rating: ${restaurant.rating} ⭐

## Top Items
${analytics.topItems?.map((item, i) => `${i + 1}. ${item.name} - ₹${item.revenue.toLocaleString()} (${item.count} orders)`).join('\n') || 'No data'}

## Order Status
${Object.entries(analytics.ordersByStatus || {}).map(([status, count]) => `- ${status}: ${count}`).join('\n')}

## Revenue by Day (Last 7 Days)
${analytics.revenueByDay?.map(day => `${day.day}: ₹${day.revenue.toLocaleString()} (${day.orders} orders)`).join('\n') || 'No data'}

---
Report generated by WaitNot Analytics System
    `.trim();

    const blob = new Blob([report], { type: 'text/markdown' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${restaurant.name}_report_${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const handleExport = async () => {
    setExporting(true);
    
    try {
      switch (exportFormat) {
        case 'csv':
          exportToCSV();
          break;
        case 'json':
          exportToJSON();
          break;
        case 'report':
          generateReport();
          break;
        default:
          exportToCSV();
      }
      
      // Show success message
      setTimeout(() => setExporting(false), 1000);
    } catch (error) {
      console.error('Export error:', error);
      setExporting(false);
    }
  };

  const shareReport = async () => {
    const text = `${restaurant.name} Analytics Report\n\nTotal Orders: ${orders.length}\nTotal Revenue: ₹${orders.reduce((sum, o) => sum + o.totalAmount, 0).toLocaleString()}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${restaurant.name} Analytics`,
          text: text
        });
      } catch (error) {
        console.log('Share cancelled');
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(text);
      alert('Report copied to clipboard!');
    }
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 border border-gray-200 dark:border-gray-700">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <Download size={20} className="text-blue-500" />
            Export Analytics
          </h3>
          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
            Download your data in various formats
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {/* Format Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Export Format
          </label>
          <div className="grid grid-cols-3 gap-3">
            <button
              onClick={() => setExportFormat('csv')}
              className={`p-3 rounded-lg border-2 transition-all ${
                exportFormat === 'csv'
                  ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                  : 'border-gray-300 dark:border-gray-600 hover:border-blue-300'
              }`}
            >
              <FileText size={24} className={`mx-auto mb-2 ${exportFormat === 'csv' ? 'text-blue-500' : 'text-gray-400'}`} />
              <p className="text-xs font-medium text-gray-900 dark:text-white">CSV</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Excel compatible</p>
            </button>

            <button
              onClick={() => setExportFormat('json')}
              className={`p-3 rounded-lg border-2 transition-all ${
                exportFormat === 'json'
                  ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                  : 'border-gray-300 dark:border-gray-600 hover:border-blue-300'
              }`}
            >
              <FileText size={24} className={`mx-auto mb-2 ${exportFormat === 'json' ? 'text-blue-500' : 'text-gray-400'}`} />
              <p className="text-xs font-medium text-gray-900 dark:text-white">JSON</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Developer friendly</p>
            </button>

            <button
              onClick={() => setExportFormat('report')}
              className={`p-3 rounded-lg border-2 transition-all ${
                exportFormat === 'report'
                  ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                  : 'border-gray-300 dark:border-gray-600 hover:border-blue-300'
              }`}
            >
              <FileText size={24} className={`mx-auto mb-2 ${exportFormat === 'report' ? 'text-blue-500' : 'text-gray-400'}`} />
              <p className="text-xs font-medium text-gray-900 dark:text-white">Report</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Markdown format</p>
            </button>
          </div>
        </div>

        {/* Export Actions */}
        <div className="flex gap-3">
          <button
            onClick={handleExport}
            disabled={exporting}
            className="flex-1 bg-blue-500 hover:bg-blue-600 text-white py-3 rounded-lg font-semibold transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            <Download size={18} />
            {exporting ? 'Exporting...' : 'Export Data'}
          </button>

          <button
            onClick={shareReport}
            className="px-4 py-3 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-900 dark:text-white rounded-lg font-semibold transition-colors flex items-center gap-2"
          >
            <Share2 size={18} />
            Share
          </button>
        </div>

        {/* Info */}
        <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4">
          <p className="text-sm text-blue-800 dark:text-blue-300">
            💡 <strong>Tip:</strong> Export your data regularly to track long-term trends and create backups.
          </p>
        </div>
      </div>
    </div>
  );
}
